/-!
# Chapter5 Tactics
-/

/-!
## Section5.1. Entering Tactic Mode
-/
section EnteringTacticMode

/-!
### Tactic: `apply`, `exact`
-/

theorem test (p q : Prop) (hp : p) (hq : q) : p ∧ q ∧ p := by
  show p ∧ q ∧ p; apply And.intro
  case left =>
    show p; exact hp
  case right =>
    show q ∧ p; apply And.intro
    case left => show q; exact hq
    case right => show p; exact hp

end EnteringTacticMode

/-!
## Section5.2. Basic Tactics
-/
section BasicTactics

/-!
### Tactic: `intro`
introduce a hypothesis
-/

example (p q r : Prop) : p ∧ (q ∨ r) ↔ (p ∧ q) ∨ (p ∧ r) := by
  apply Iff.intro
  show p ∧ (q ∨ r) → (p ∧ q) ∨ (p ∧ r)
  intro h
  · show (p ∧ q) ∨ (p ∧ r)
    apply Or.elim h.right
    · show q → (p ∧ q) ∨ (p ∧ r)
      intro hq
      show (p ∧ q) ∨ (p ∧ r)
      apply Or.inl
      show p ∧ q
      have hp : p := h.left
      exact And.intro hp hq
    · show r → (p ∧ q) ∨ (p ∧ r)
      intro hr
      show (p ∧ q) ∨ (p ∧ r)
      apply Or.inr
      show p ∧ r
      have hp : p := h.left
      exact And.intro hp hr
  · show (p ∧ q) ∨ (p ∧ r) → p ∧ (q ∨ r)
    intro (h : (p ∧ q) ∨ (p ∧ r))
    show p ∧ (q ∨ r)
    apply Or.elim h
    · show p ∧ q → p ∧ (q ∨ r)
      intro (h : p ∧ q)
      show p ∧ (q ∨ r)
      have hp : p := h.left
      apply And.intro hp
      show q ∨ r
      have hq : q := h.right
      exact Or.inl hq
    · show p ∧ r → p ∧ (q ∨ r)
      intro (h : p ∧ r)
      show p ∧ (q ∨ r)
      have hp : p := h.left
      apply And.intro hp
      show q ∨ r
      have hr : r := h.right
      exact Or.inr hr

example (α : Type) : ∀ x : α, x = x := by
  show ∀ x : α, x = x
  intro (x : α)
  show x = x
  apply Eq.refl x

example : ∀ a b c : Nat, a = b → a = c → c = b := by
  intro a b c hab hac
  show c = b
  apply Eq.trans
  · show c = a
    exact Eq.symm hac
  · show a = b
    exact hab

example (α : Type) (p q : α → Prop) : (∃ x, p x ∧ q x) → ∃ x, q x ∧ p x := by
  intro (Exists.intro w (And.intro hp hq : p w ∧ q w) : ∃ x, p x ∧ q x)
  exact Exists.intro w (And.intro hq hp)

example (α : Type) (p q : α → Prop) : (∃ x, p x ∨ q x) → ∃ x, q x ∨ p x := by
  intro
  | (Exists.intro w (Or.inl hp : p w ∨ q w) : ∃ x, p x ∨ q x) =>
    exact Exists.intro w (Or.inr hp)
  | (Exists.intro w (Or.inr hq : p w ∨ q w) : ∃ x, p x ∨ q x) =>
    exact Exists.intro w (Or.inl hq)

/-!
### Tactic: `assumption`
looks though the assumptions in context of the current goal, and if there is one
matching the conclusion, it applies it
-/

example (x y z w : Nat) (h₁ : x = y) (h₂ : y = z) (h₃ : z = w) : x = w := by
  apply Eq.trans
  assumption -- exact h₁
  show y = w
  apply Eq.trans
  assumption -- exact h₂
  show z = w
  assumption -- exact h₃

/-!
### Tactic: `intros` & Combinator: `unhygienic`
Names automatically generated by Lean are inaccessible by default. The
motivation is to ensure your tactic proofs do not rely on automatically
generated names, and are consequently more robust. However, you can use the
combinator `unhygienic` to disable this restriction.
-/
example : ∀ a b c : Nat, a = b → a = c → c = b := by unhygienic
  intros
  apply Eq.trans
  apply Eq.symm
  exact a_2 -- assumption
  exact a_1 -- assumption

/-!
### Tactic: `intros` & `rename_i`
Use the `rename_i` tactic to rename the most recent inaccessible names in the
context.
-/
example : ∀ a b c d : Nat, a = b → a = d → a = c → c = b := by
  intros
  rename_i h₁ _ h₂
  apply Eq.trans
  apply Eq.symm
  exact h₂
  exact h₁

/-!
### Tactic: `rfl`
-/
example (y : Nat) : ((λ _ : Nat => 0) y) = 0 := by
  rfl -- exact rfl

/-!
### Combinator: `repeat`
Apply a tactic several times.
-/
example : ∀ a b c : Nat, a = b → a = c → c = b := by
  intros
  apply Eq.trans
  apply Eq.symm
  repeat assumption

/-!
### Tactic: `revert`
Inverse to `intro`.
-/

example (x : Nat) : x = x := by
  show x = x
  revert x
  show ∀ x : Nat, x = x
  show (x : Nat) → x = x
  intro y
  show y = y
  rfl

example (x y : Nat) (h : x = y) : y = x := by
  show y = x
  revert h
  show x = y → y = x
  apply Eq.symm
  -- show ∀ h : x = y, y = x
  -- intro (h₁ : x = y)
  -- show y = x
  -- apply Eq.symm
  -- show x = y
  -- assumption

/--
NOTE THAT: `revert` will revert not only an element of the context but also all
the subsequent elements of the context that depend on it.
-/
example (x y : Nat) (h : x = y) : y = x := by
  show y = x
  revert x y -- `revert` reverts not only `x` `y` but also `h`.
  show (x : Nat) → (y : Nat) → x = y → y = x
  intros
  apply Eq.symm
  assumption

/-!
### Tactic: `generalize`
Replace an arbitrary expression in the goal by a fresh variable.
-/

example : 3 = 3 := by
  generalize 3 = x
  show x = x
  revert x
  show (x : Nat) → x = x
  intro (y : Nat)
  show y = y
  apply Eq.refl y

axiom admit_axiom : ∀ x : Nat, 2 + x = 5
/--
Not every generalization preserves the validity of the goal.
-/
example : 2 + 3 = 5 := by
  generalize 3 = x
  show 2 + x = 5 -- `generalize` replace a goal that could be proved using `rfl`
  -- with one that is not provable.
  revert x
  show ∀ x : Nat, 2 + x = 5
  apply admit_axiom

/--
`rw` tactic can use `h` to replace `x` again.
-/
example : 2 + 3 = 5 := by
  generalize h : 3 = x
  show 2 + x = 5
  rw [← h]

end BasicTactics

/-!
## Section5.3. More Tactics
-/
section MoreTactics

/-!
### Tactic: `cases`
Decompose a disjunction.
-/

example (p q : Prop) : p ∨ q → q ∨ p := by
  intro h
  show q ∨ p
  cases h with
  | inl hp =>
    show q ∨ p
    apply Or.inr
    show p
    exact hp
  | inr hq =>
    show q ∨ p
    apply Or.inl
    show q
    exact hq

/--
The unstructured `cases` is particularly useful when you can close several
subgoals using the same tactic.
-/
example (p : Prop) : p ∨ p → p := by
  intro h
  cases h
  repeat assumption

/--
Use the combinator `tac₁ <;> tac₂` to apply `tac₂` to each subgoal produced by
tactic `tac₁`
-/
example (p : Prop) : p ∨ p → p := by
  intro h
  cases h <;> assumption

end MoreTactics

section StructuringTacticProofs
end StructuringTacticProofs

section TacticCombinators
end TacticCombinators

section Rewriting
end Rewriting

section UsingTheSimplifier
end UsingTheSimplifier

section SplitTactic
end SplitTactic

section ExtensibleTactics
end ExtensibleTactics

section Exercises
end Exercises
