/-!
# Chapter5 Tactics
-/

/-!
## Section5.1. Entering Tactic Mode
-/
section EnteringTacticMode

/-!
### Tactic: `apply`, `exact`
-/

theorem test (p q : Prop) (hp : p) (hq : q) : p ∧ q ∧ p := by
  show p ∧ q ∧ p; apply And.intro
  case left =>
    show p; exact hp
  case right =>
    show q ∧ p; apply And.intro
    case left => show q; exact hq
    case right => show p; exact hp

end EnteringTacticMode

/-!
## Section5.2. Basic Tactics
-/
section BasicTactics

/-!
### Tactic: `intro`
introduce a hypothesis
-/

example (p q r : Prop) : p ∧ (q ∨ r) ↔ (p ∧ q) ∨ (p ∧ r) := by
  apply Iff.intro
  show p ∧ (q ∨ r) → (p ∧ q) ∨ (p ∧ r)
  intro h
  · show (p ∧ q) ∨ (p ∧ r)
    apply h.right.elim
    · show q → (p ∧ q) ∨ (p ∧ r)
      intro hq
      show (p ∧ q) ∨ (p ∧ r)
      apply Or.inl
      show p ∧ q
      have hp : p := h.left
      exact And.intro hp hq
    · show r → (p ∧ q) ∨ (p ∧ r)
      intro hr
      show (p ∧ q) ∨ (p ∧ r)
      apply Or.inr
      show p ∧ r
      have hp : p := h.left
      exact And.intro hp hr
  · show (p ∧ q) ∨ (p ∧ r) → p ∧ (q ∨ r)
    intro (h : (p ∧ q) ∨ (p ∧ r))
    show p ∧ (q ∨ r)
    apply h.elim
    · show p ∧ q → p ∧ (q ∨ r)
      intro (h : p ∧ q)
      show p ∧ (q ∨ r)
      have hp : p := h.left
      apply And.intro hp
      show q ∨ r
      have hq : q := h.right
      exact Or.inl hq
    · show p ∧ r → p ∧ (q ∨ r)
      intro (h : p ∧ r)
      show p ∧ (q ∨ r)
      have hp : p := h.left
      apply And.intro hp
      show q ∨ r
      have hr : r := h.right
      exact Or.inr hr

example (α : Type) : ∀ x : α, x = x := by
  show ∀ x : α, x = x
  intro (x : α)
  show x = x
  apply Eq.refl x

example : ∀ a b c : Nat, a = b → a = c → c = b := by
  intro a b c hab hac
  show c = b
  apply Eq.trans
  · show c = a
    exact Eq.symm hac
  · show a = b
    exact hab

example (α : Type) (p q : α → Prop) : (∃ x, p x ∧ q x) → ∃ x, q x ∧ p x := by
  intro (Exists.intro w (And.intro hp hq : p w ∧ q w) : ∃ x, p x ∧ q x)
  exact Exists.intro w (And.intro hq hp)

example (α : Type) (p q : α → Prop) : (∃ x, p x ∨ q x) → ∃ x, q x ∨ p x := by
  intro
  | (Exists.intro w (Or.inl hp : p w ∨ q w) : ∃ x, p x ∨ q x) =>
    exact Exists.intro w (Or.inr hp)
  | (Exists.intro w (Or.inr hq : p w ∨ q w) : ∃ x, p x ∨ q x) =>
    exact Exists.intro w (Or.inl hq)

/-!
### Tactic: `assumption`
looks though the assumptions in context of the current goal, and if there is one
matching the conclusion, it applies it
-/

example (x y z w : Nat) (h₁ : x = y) (h₂ : y = z) (h₃ : z = w) : x = w := by
  apply Eq.trans
  assumption -- exact h₁
  show y = w
  apply Eq.trans
  assumption -- exact h₂
  show z = w
  assumption -- exact h₃

/-!
### Tactic: `intros` & Combinator: `unhygienic`
Names automatically generated by Lean are inaccessible by default. The
motivation is to ensure your tactic proofs do not rely on automatically
generated names, and are consequently more robust. However, you can use the
combinator `unhygienic` to disable this restriction.
-/
example : ∀ a b c : Nat, a = b → a = c → c = b := by unhygienic
  intros
  apply Eq.trans
  apply Eq.symm
  exact a_2 -- assumption
  exact a_1 -- assumption

/-!
### Tactic: `intros` & `rename_i`
Use the `rename_i` tactic to rename the most recent inaccessible names in the
context.
-/
example : ∀ a b c d : Nat, a = b → a = d → a = c → c = b := by
  intros
  rename_i h₁ _ h₂
  apply Eq.trans
  apply Eq.symm
  exact h₂
  exact h₁

/-!
### Tactic: `rfl`
-/
example (y : Nat) : ((λ _ : Nat => 0) y) = 0 := by
  rfl -- exact rfl

/-!
### Combinator: `repeat`
Apply a tactic several times.
-/
example : ∀ a b c : Nat, a = b → a = c → c = b := by
  intros
  apply Eq.trans
  apply Eq.symm
  repeat assumption

/-!
### Tactic: `revert`
Inverse to `intro`.
-/

example (x : Nat) : x = x := by
  show x = x
  revert x
  show ∀ x : Nat, x = x
  show (x : Nat) → x = x
  intro y
  show y = y
  rfl

example (x y : Nat) (h : x = y) : y = x := by
  show y = x
  revert h
  show x = y → y = x
  apply Eq.symm
  -- show ∀ h : x = y, y = x
  -- intro (h₁ : x = y)
  -- show y = x
  -- apply Eq.symm
  -- show x = y
  -- assumption

/--
NOTE THAT: `revert` will revert not only an element of the context but also all
the subsequent elements of the context that depend on it.
-/
example (x y : Nat) (h : x = y) : y = x := by
  show y = x
  revert x y -- `revert` reverts not only `x` `y` but also `h`.
  show (x : Nat) → (y : Nat) → x = y → y = x
  intros
  apply Eq.symm
  assumption

/-!
### Tactic: `generalize`
Replace an arbitrary expression in the goal by a fresh variable.
-/

example : 3 = 3 := by
  generalize 3 = x
  show x = x
  revert x
  show (x : Nat) → x = x
  intro (y : Nat)
  show y = y
  apply Eq.refl y

axiom admit_axiom : ∀ x : Nat, 2 + x = 5
/--
Not every generalization preserves the validity of the goal.
-/
example : 2 + 3 = 5 := by
  generalize 3 = x
  show 2 + x = 5 -- `generalize` replace a goal that could be proved using `rfl`
  -- with one that is not provable.
  revert x
  show ∀ x : Nat, 2 + x = 5
  apply admit_axiom

/--
`rw` tactic can use `h` to replace `x` again.
-/
example : 2 + 3 = 5 := by
  generalize h : 3 = x
  show 2 + x = 5
  rw [← h]

end BasicTactics

/-!
## Section5.3. More Tactics
-/
section MoreTactics

/-!
### Tactic: `cases`
Decompose a disjunction.
-/

example (p q : Prop) : p ∨ q → q ∨ p := by
  intro h
  show q ∨ p
  cases h with
  | inl hp =>
    show q ∨ p
    apply Or.inr
    show p
    exact hp
  | inr hq =>
    show q ∨ p
    apply Or.inl
    show q
    exact hq

/--
The unstructured `cases` is particularly useful when you can close several
subgoals using the same tactic.
-/
example (p : Prop) : p ∨ p → p := by
  intro h
  cases h
  repeat assumption

/--
Use the combinator `tac₁ <;> tac₂` to apply `tac₂` to each subgoal produced by
tactic `tac₁`
-/
example (p : Prop) : p ∨ p → p := by
  intro h
  cases h <;> assumption

/--
### Tactic: `constructor`
Applies the unique constructor for conjunction.
-/
example (p q : Prop) : p ∧ q → q ∧ p := by
  intro (h : p ∧ q)
  cases h with
  | intro hp hq =>
    constructor
    · exact hq
    · exact hp

example (p q r : Prop) : p ∧ (q ∨ r) ↔ (p ∧ q) ∨ (p ∧ r) := by
  constructor -- apply Iff.intro
  · show p ∧ (q ∨ r) → (p ∧ q) ∨ (p ∧ r)
    intro (h : p ∧ (q ∨ r))
    show (p ∧ q) ∨ (p ∧ r)
    cases h with
    | intro hp hqr =>
      show (p ∧ q) ∨ (p ∧ r)
      cases hqr with
      | inl hq =>
        show (p ∧ q) ∨ (p ∧ r)
        apply Or.inl
        show p ∧ q
        constructor -- And.intro
        · exact hp
        · exact hq
      | inr hr =>
        show (p ∧ q) ∨ (p ∧ r)
        apply Or.inr
        show p ∧ r
        constructor -- And.intro
        · exact hp
        · exact hr
  · show (p ∧ q) ∨ (p ∧ r) → p ∧ (q ∨ r)
    intro (h : (p ∧ q) ∨ (p ∧ r))
    show p ∧ (q ∨ r)
    cases h with
    | inl hpq =>
      show p ∧ (q ∨ r)
      cases hpq with
      | intro hp hq =>
        show p ∧ (q ∨ r)
        constructor
        · exact hp
        · exact Or.inl hq
    | inr hpr =>
      show p ∧ (q ∨ r)
      cases hpr with
      | intro hp hr =>
        show p ∧ (q ∨ r)
        constructor
        · exact hp
        · exact Or.inr hr

example (p q : Nat → Prop) : (∃ x, p x) → ∃ x, p x ∨ q x := by
  intro (h : ∃ x, p x)
  show ∃ x, p x ∨ q x
  cases h with
  | intro x px =>
    show ∃ x, p x ∨ q x
    -- constructor -- same with below
    exists x -- same with above
    show p x ∨ q x
    apply Or.inl
    show p x
    exact px

example (p q : Nat → Prop) : (∃ x, p x ∧ q x) → ∃ x, q x ∧ p x := by
  intro (h : ∃ x, p x ∧ q x)
  show ∃ x, q x ∧ p x
  cases h with
  | intro w hpq =>
    show ∃ x, q x ∧ p x
    cases hpq with
    | intro hp hq =>
      show ∃ x, q x ∧ p x
      exists w

def swap_pair : α × β → β × α := by
  intro (p : α × β)
  show β × α
  cases p
  show β × α
  constructor <;> assumption
#eval swap_pair (1, 2)
def swap_sum : α ⊕ β → β ⊕ α := by
  intro (p : α ⊕ β)
  show β ⊕ α
  cases p
  · show β ⊕ α
    apply Sum.inr
    show α
    assumption
  · show β ⊕ α
    apply Sum.inl
    show β
    assumption

example (P : Nat → Prop) (h₀ : P 0) (h₁ : ∀ n, P (Nat.succ n)) (m : Nat)
: P m := by
  cases m with
  | zero =>
    show P 0
    exact h₀
  | succ m' =>
    show P (m' + 1)
    exact h₁ m'

/-!
### Tactic: `contradiction`
Search for a contradiction among the hypotheses of the current goal.
-/

example (p q : Prop) : p ∧ ¬p → q := by
  intro (h : p ∧ ¬p)
  show q
  cases h
  contradiction

example (p q r : Prop) : p ∧ (q ∨ r) ↔ (p ∧ q) ∨ (p ∧ r) := by
  constructor
  · show p ∧ (q ∨ r) → (p ∧ q) ∨ (p ∧ r)
    -- intro (h : p ∧ (q ∨ r))
    -- show (p ∧ q) ∨ (p ∧ r)
    -- match h with
    intro -- Combine `intro` with `match`.
    | And.intro (hp : p) (Or.inl (hq : q)) =>
      apply Or.inl
      show p ∧ q
      exact And.intro hp hq
    | And.intro (hp : p) (Or.inr (hr : r)) =>
      apply Or.inr
      show p ∧ r
      exact And.intro hp hr
  · show (p ∧ q) ∨ (p ∧ r) → p ∧ (q ∨ r)
    -- intro (h : (p ∧ q) ∨ (p ∧ r))
    -- show p ∧ (q ∨ r)
    -- match h with
    intro -- Combine `intro` with `match`.
    | Or.inl (And.intro (hp : p) (hq : q)) =>
      constructor
      · exact hp
      · show q ∨ r
        exact Or.inl hq
    | Or.inr (And.intro (hp : p) (hr : r)) =>
      constructor
      · exact hp
      · show q ∨ r
        exact Or.inr hr

end MoreTactics

/-!
## Section5.4 Structing Tactic Proofs
-/
section StructuringTacticProofs

/--
### How to mix term-style and tactic-style proofs.
-/
example (p q r : Prop) : p ∧ (q ∨ r) → (p ∧ q) ∨ (p ∧ r) := by
  -- switch to tactic mode
  intro h
  exact
    -- switch to term mode
    show (p ∧ q) ∨ (p ∧ r) from
    have hp : p := h.left
    have hqr : q ∨ r := h.right
    show (p ∧ q) ∨ (p ∧ r) by
    -- switch to tactic mode
    -- cases hqr
    -- · apply Or.inl; constructor <;> assumption
    -- · apply Or.inr; constructor <;> assumption
    -- cases hqr
    -- case inl hq => apply Or.inl; constructor <;> assumption
    -- case inr hr => apply Or.inr; constructor <;> assumption
    cases hqr with
    | inl hq => apply Or.inl; constructor <;> assumption
    | inr hr => apply Or.inr; constructor <;> assumption

/--
### Tactic: `show`
Declare the type of the goal that is about to be solved, while remaining in
tactic mode.
Rewrite a goal to something definitionally equivalent.
-/
example (n : Nat) : n + 1 = Nat.succ n := by
  show n + 1 = Nat.succ n
  show Nat.succ n = Nat.succ n
  show n + 1 = n + 1
  rfl

/--
### Tactic: `have`
- Introduces a new subgoal.
- Label can be omitted, in which case, the default label `this` is used.
- Type can be ommited.
-/
example (p q r : Prop) : p ∧ (q ∨ r) → (p ∧ q) ∨ (p ∧ r) := by
  intro ⟨hp, hqr⟩
  cases hqr with
  | inl hq =>
    have := And.intro hp hq
    apply Or.inl; exact this
  | inr hr =>
    have := And.intro hp hr
    apply Or.inr; assumption

/--
### Tactic: `let`
- Intruduces local definitions instead of auxiliary facts.
- Difference with `have`: `let` introduces a local definition in the context, so
  that the definition of the local declaration can be unfolded in the proof.
-/
example : ∃ x, x + 2 = 8 := by
  let a : Nat := 3 * 2
  have b : Nat := 3 * 2
  -- exists b -- Error!
  exists a

end StructuringTacticProofs

/-!
## Section5.5 Tactic Combinators
-/
section TacticCombinators

/-!
### Tactic: `first | t₁ | t₂ | ... | tₙ`
Applies each `tᵢ` until one succeeds, or else fails; 
-/

example (p q : Prop) (hp : p) : p ∨ q := by
  first
  -- | sorry -- WARNING
  | apply Or.inl; assumption
  | apply Or.inr; assumption

example (p q r : Prop) (hp : r) : p ∨ q ∨ r := by
  repeat first
  | apply Or.inl; assumption
  | apply Or.inr
  | assumption

/--
Please read the comment of this example to help you to understand Exercise2.
-/
example (p q r : Prop) (hp : r) : p ∨ q ∨ r := by
  first
  | apply Or.inl; assumption
    -- Cannot remove `; assumption` because we do not want to `apply Or.inl`
    -- success but want to `apply Or.inl; assumption` failed at this step.
  | apply Or.inr
  | assumption
  show q ∨ r
  first
  | apply Or.inl; assumption
  | apply Or.inr
  | assumption
  show r
  first
  | apply Or.inl; assumption
  | apply Or.inr
  | assumption

/-!
### Tactic: `try`
-/

example (p q r : Prop) (hp : p) (hq : q) (hr : r) : p ∧ q ∧ r := by
  constructor
  · exact hp
  · constructor
    case left => exact hq
    case right => exact hr

example (p q r : Prop) (hp : p) (hq : q) (hr : r) : p ∧ q ∧ r := by
  constructor <;> (first | constructor | skip) <;> assumption

example (p q r : Prop) (hp : p) (hq : q) (hr : r) : p ∧ q ∧ r := by
  constructor <;> (try constructor) <;> assumption

/--
### Tactic: `all_goals`
`all_goals t` applies `t` to all open goals.
-/
example (p q r : Prop) (hp : p) (hq : q) (hr : r) : p ∧ q ∧ r := by
  constructor
  -- 2goals
  -- case left ⊢ p
  -- case right ⊢ q ∧ r
  all_goals (try constructor)
  -- 3goals
  -- case left ⊢ p
  -- case right.left ⊢ q
  -- case right.right ⊢ r
  all_goals assumption
  -- 0goals

/--
### Tactic: `any_goals`
`any_goals t` applies `t` to all open goals, and succeeds on at least one goal,
maybe is like `all_goals (try t)`.
-/
example (p q r : Prop) (hp : p) (hq : q) (hr : r) : p ∧ q ∧ r := by
  constructor
  any_goals constructor
  all_goals assumption

example (p q r : Prop) (hp : p) (hq : q) (hr : r)
: p ∧ ((p ∧ q) ∧ r) ∧ (q ∧ r ∧ p) := by
  -- repeat (any_goals constructor)
  -- all_goals assumption
  repeat (any_goals (first | constructor | assumption))

end TacticCombinators

/-!
## Section5.6 Rewriting
-/
section Rewriting

/-!
### Tactic: rw
-/

/-!
- Rewrite a hypothesis `h : x = y`.
- Rewrite a lemma `add_comm : ∀ x y, x + y = y + x`, in which the rewrite tactic
  tries to find suitable instantiations of `x` and `y`.
- Rewrite a compound term asserting a concrete.
- Rewrite a general equation.
-/

example (f : Nat → Nat) (k : Nat) (h₁ : f 0 = 0) (h₂ : k = 0) : f k = 0 := by
  show f k = 0
  rw [h₂] -- k = 0
  show f 0 = 0
  rw [h₁] -- f 0 = 0
  -- show 0 = 0, automatically closed by `rw` tactic because the tactic will
  -- automatically closes any goal of the form `t = t`.

example (x y : Nat) (p : Nat → Prop) (q : Prop)
  (h : q → x = y) (h' : p y) (hq : q)
: p x := by
  show p x
  rw [h hq] -- h hq : x = y
  show p y
  exact h'

/--
- `rw [t₁, ..., tₙ]` as same as `rw [t₁]; ...; rw [tₙ]`.
- By default, `rw` uses an equation in the forward direction, matching the
  left-hand side with an expression, and replacing it with the right-hand side.
  The notation `←t` can be used to instruct the tactic to use the equality `t`
  in the reverse direction.
-/
example (f : Nat → Nat) (a b : Nat) (h₁ : a = b) (h₂ : f a = 0) : f b = 0 := by
  rw [←h₁, h₂]

/--
- `rw` tactic chooses the first match it finds when traversing the term. To use
  additional arguments can specify the appropriate subterm.
-/
example (a b c : Nat) : a + b + c = a + c + b := by
  show a + b + c = a + c + b
  rw [Nat.add_assoc]
  show a + (b + c) = a + c + b
  rw [Nat.add_comm b]
  --↑ The left-hand side of this identity can match more than one subterm in the
  --↑ pattern, without specifying the argument, the tactic would instead rewrite
  --↑ `a + (b + c)` to `(b + c) + a`.
  show a + (c + b) = a + c + b
  rw [←Nat.add_assoc]

/--
- By default, the `rw` tactic affects only the goal. The notation `rw [t] at h`
  applies the rewrite for `h` but not the goal.
-/
example (f : Nat → Nat) (a : Nat) (h : a + 0 = 0) : f a = f 0 := by
  show f a = f 0
  rw [Nat.add_zero] at h
  show f a = f 0 -- No effect at goal.
  rw [h]

def Tuple (α : Type) (n : Nat) :=
  { as : List α // as.length = n }
example {α : Type} (n : Nat) (h : n = 0) (t : Tuple α n) : Tuple α 0 := by
  rw [h] at t
  exact t

end Rewriting

/-!
## Section5.7 Using the Simplifier
-/
section UsingTheSimplifier

/-!
Tactic: `simp`
-/

/-!
- The `simp` tactic uses identities which in Lean's library have been tagged
  with the `[simp]` attribute to iteratively rewrite subterms in an expression.
-/

example (x y z : Nat) : (x + 0) * (0 + y * 1 + z * 0) = x * y := by
  simp

example (x y z : Nat) (p : Nat → Prop) (h : p (x * y))
: p ((x + 0) * (0 + y * 1 + z * 0)) := by
  simp
  show p (x * y)
  exact h

example (xs : List Nat)
: List.reverse (xs ++ [1, 2, 3]) = [3, 2, 1] ++ List.reverse xs := by
  simp

example {α : Type} (xs ys : List α)
: List.length (List.reverse (xs ++ ys)) = List.length xs + List.length ys := by
  simp [Nat.add_comm]
  -- simp
  -- apply Nat.add_comm

/--
- By default, the `simp` tactic affects only the goal. The notation `simp at h`
  applies the simplifier for `h` but not the goal. Moreover, `simp at *`
  asterisk to simplify all the hypotheses and the goal.
-/

example (x y z : Nat)
  (p : Nat → Prop) (h : p ((x + 0) * (0 + y * 1 + z * 0)))
: p (x * y) := by
  simp at h
  exact h

section
-- attribute [local simp] Nat.mul_comm Nat.mul_assoc Nat.mul_left_comm
-- attribute [local simp] Nat.add_assoc Nat.add_comm Nat.add_left_comm
attribute [local simp] Nat.mul_comm Nat.mul_left_comm -- Let `simp` be able to
attribute [local simp] Nat.add_comm -- use these theorem inside this section.
example (w x y z : Nat)
  (p : Nat → Prop) (h : p (x * y + z * w * x))
: p (x * w * z + y * x) := by
  simp at *
  assumption
end
/--
- `simp [t₁, ..., tₙ]` as same as `simp [t₁]; ...; simp [tₙ]`.
- By default, `simp` uses an equation in the forward direction, matching the
  left-hand side with an expression, and replacing it with the right-hand side.
  The notation `←t` can be used to instruct the tactic to use the equality `t`
  in the reverse direction.
-/
example (w x y z : Nat)
  (p : Nat → Prop) (h : p (x * y + z * w * x))
: p (x * w * z + y * x) := by
  simp [ Nat.mul_comm, Nat.mul_left_comm, Nat.add_comm] at *
  --↑ Same with last example in paragraph above.
  assumption

/--
- Use the `simp [*]` to use all the hypotheses present in the local context when
  simplifying
-/
example (f : Nat → Nat) (k : Nat) (h₁ : f 0 = 0) (h₂ : k = 0) : f k = 0 := by
  simp [*]

example (p q : Prop) (hp : p) : p ∧ q ↔ q := by
  simp [*]
  -- constructor
  -- · show p ∧ q → q
  --   intro hpq
  --   exact hpq.right
  -- · show q → p ∧ q
  --   intro hq
  --   constructor <;> assumption
example (p q : Prop) (hp : p) : p ∨ q := by
  simp [*]
  -- exact Or.inl hp

example (u w x x' y y' z : Nat) (p : Nat → Prop)
  (h₁ : x + 0 = x') (h₂ : y + 0 = y')
: x + y + 0 = x' + y' := by
  -- simp [*] at * NO WAY!!!
  simp at *
  simp [*]

/-!
- `@[simp] theorem t ...` declares theorem `t` to have the [simp] attribute.
-/
section
def mk_symm {α : Type} (xs : List α) := xs ++ xs.reverse
-- @[simp]
theorem reverse_mk_symm {α : Type} (xs : List α)
: (mk_symm xs).reverse = mk_symm xs := by
  simp [mk_symm]
attribute [local simp] reverse_mk_symm
example (xs ys : List Nat)
: (xs ++ mk_symm ys).reverse = mk_symm ys ++ xs.reverse := by
  -- simp [reverse_mk_symm]
  simp
/--
- `simp [-t]` is used to block the application of `t`.
- `simp only [t]` is used to apply the application of `t` only.
-/
example (xs ys : List Nat) (p : List Nat → Prop)
  (h : p (xs ++ mk_symm ys).reverse)
: p ((mk_symm ys).reverse ++ xs.reverse) := by
  -- simp [-reverse_mk_symm] at h
  simp only [List.reverse_append] at h
  assumption
end

/-!
- `simp` tactic has many configuration options. `simp +configuration` to use
  them.
  - `simp +contextual`
  - `simp +arith` or `simp_arith`
-/

example : if x = 0 then y + x = y else x ≠ 0 := by
  simp +contextual

example : ∀ (x : Nat) (h : x = 0), y + x = y := by
  simp +contextual

example : 0 < 1 + x ∧ x + y + 2 ≥ y + 1 := by
  simp +arith

end UsingTheSimplifier

/-!
## Section5.8 Split Tactic
-/
section SplitTactic

def f (x y z : Nat) : Nat :=
  match x, y, z with
  | 5, _, _ => y
  | _, 5, _ => y
  | _, _, 5 => y
  | _, _, _ => 1

example (x y z : Nat) : x ≠ 5 → y ≠ 5 → z ≠ 5 → z = w → f x y w = 1 := by
  intro h₁ h₂ h₃ h₄
  show f x y w = 1
  simp [f]
  show (
    match x, y, w with
    | 5, _, _ => y
    | _, 5, _ => y
    | _, _, 5 => y
    | _, _, _ => 1
  ) = 1
  split
  · show y = 1;
    -- h₁ : 5 ≠ 5
    contradiction
  · show 5 = 1
    -- h₂ : 5 ≠ 5
    contradiction
  · show y = 1
    -- h₃ : z ≠ 5, h₄ : z = 5
    apply absurd h₄ h₃
  · show 1 = 1
    apply Eq.refl

def g (xs ys : List Nat) : Nat :=
  match xs, ys with
  | [a, b], _ => a + b + 1
  | _, [b, _c] => b + 1
  | _, _ => 1

example (xs ys : List Nat) (h : g xs ys = 0) : False := by
  have h : (
    match xs, ys with
    | [a, b], _ => a + b + 1
    | _, [b, _c] => b + 1
    | _, _ => 1
  ) = 0 := by
    simp [g] at h
    exact h
  split at h <;> simp +arith at h

end SplitTactic

/-!
## Section5.9 Extensible Tactic
-/
section ExtensibleTactics

syntax "triv" : tactic

macro_rules
| `(tactic| triv) => `(tactic| assumption)
example (h : p) : p := by
  assumption
example (h : p) : p := by
  triv

macro_rules
| `(tactic| triv) => `(tactic| rfl)
example : p = p := by
  triv

end ExtensibleTactics

/-!
## Section5.10 Exercises
-/
section Exercises

/-!
1. Go back to the exercises in Propositions and Proofs and Quantifiers and
  Equality and redo as many as you can now with tactic proofs, using also `rw`
  and `simp` as appropriate.
-/
section Exercise1

section PropositionsAndProofs

/-!
Prove the following identities, replacing the `sorry` placeholders with actual
proofs.
-/
section

variable (p q r : Prop)

-- commutativity of `∧` and `∨`
example : p ∧ q ↔ q ∧ p := by apply And.comm
example : p ∨ q ↔ q ∨ p := by apply Or.comm

-- associativity of `∧` and `∨`
example : (p ∧ q) ∧ r ↔ p ∧ (q ∧ r) := by
  constructor
  · show (p ∧ q) ∧ r → p ∧ (q ∧ r)
    intro (And.intro (And.intro hp hq) hr)
    repeat any_goals constructor
    repeat assumption
  · show p ∧ (q ∧ r) → (p ∧ q) ∧ r
    intro (And.intro hp (And.intro hq hr))
    repeat any_goals constructor
    repeat assumption
example : (p ∨ q) ∨ r ↔ p ∨ (q ∨ r) := by
  constructor
  · show (p ∨ q) ∨ r → p ∨ (q ∨ r)
    intro
    | Or.inl (Or.inl hp) => exact Or.inl hp
    | Or.inl (Or.inr hq) => exact Or.inr ∘ Or.inl $ hq
    | Or.inr hr => exact Or.inr ∘ Or.inr $ hr
  · show p ∨ (q ∨ r) → (p ∨ q) ∨ r
    intro
    | Or.inl hp => exact Or.inl ∘ Or.inl $ hp
    | Or.inr (Or.inl hq) => exact Or.inl ∘ Or.inr $ hq
    | Or.inr (Or.inr hr) => exact Or.inr hr

-- distributivity
example : p ∧ (q ∨ r) ↔ (p ∧ q) ∨ (p ∧ r) := by
  constructor
  · show p ∧ (q ∨ r) → (p ∧ q) ∨ (p ∧ r)
    intro
    | And.intro hp (Or.inl hq) => exact Or.inl (And.intro hp hq)
    | And.intro hp (Or.inr hr) => exact Or.inr (And.intro hp hr)
  · show (p ∧ q) ∨ (p ∧ r) → p ∧ (q ∨ r)
    intro
    | Or.inl (And.intro hp hq) => exact And.intro hp $ Or.inl hq
    | Or.inr (And.intro hp hr) => exact And.intro hp $ Or.inr hr
example : p ∨ (q ∧ r) ↔ (p ∨ q) ∧ (p ∨ r) := by
  constructor
  · show p ∨ (q ∧ r) → (p ∨ q) ∧ (p ∨ r)
    intro
    | Or.inl hp => exact And.intro (Or.inl hp) (Or.inl hp)
    | Or.inr (And.intro hq hr) => exact And.intro (Or.inr hq) (Or.inr hr)
  · show (p ∨ q) ∧ (p ∨ r) → p ∨ (q ∧ r)
    intro
    | And.intro (Or.inl hp) (Or.inl hp') => exact Or.inl hp
    | And.intro (Or.inl hp) (Or.inr hr) => exact Or.inl hp
    | And.intro (Or.inr hq) (Or.inl hp) => exact Or.inl hp
    | And.intro (Or.inr hq) (Or.inr hr) => exact Or.inr $ And.intro hq hr

-- other properties
example : (p → (q → r)) ↔ (p ∧ q → r) := by
  constructor
  · show (p → (q → r)) → (p ∧ q → r)
    intro h
    show p ∧ q → r
    intro (And.intro hp hq)
    show r
    exact h hp hq
  · show (p ∧ q → r) → (p → (q → r))
    intro h
    intro hp
    intro hq
    exact h (And.intro hp hq)
example : ((p ∨ q) → r) ↔ (p → r) ∧ (q → r) := by
  constructor
  · show ((p ∨ q) → r) → (p → r) ∧ (q → r)
    intro h
    constructor
    · show p → r
      intro hp
      exact h (Or.inl hp)
    · show q → r
      intro hq
      exact h (Or.inr hq)
  · show (p → r) ∧ (q → r) → ((p ∨ q) → r)
    intro h
    intro
    | Or.inl hp => exact h.left hp
    | Or.inr hq => exact h.right hq
example : ¬(p ∨ q) ↔ ¬p ∧ ¬q := by
  constructor
  · show ¬(p ∨ q) → ¬p ∧ ¬q
    intro h
    constructor
    · show ¬p
      intro hp
      exact h (Or.inl hp)
    · show ¬q
      intro hq
      exact h (Or.inr hq)
  · show ¬p ∧ ¬q → ¬(p ∨ q)
    intro (And.intro hnp hnq)
    intro
    | Or.inl hp => exact hnp hp
    | Or.inr hq => exact hnq hq
example : ¬p ∨ ¬q → ¬(p ∧ q) := by
  intro
  | Or.inl hnp =>
    intro h
    exact hnp h.left
  | Or.inr hnq =>
    intro h
    exact hnq h.right
example : ¬(p ∧ ¬p) := by
  intro (And.intro hp hnp)
  exact hnp hp
example : p ∧ ¬q → ¬(p → q) := by
  intro (And.intro hp hnq)
  intro h
  exact hnq $ h hp
example : ¬p → (p → q) := by
  intro hnp
  intro hp
  exact absurd hp hnp
example : (¬p ∨ q) → (p → q) := by
  intro
  | Or.inl hnp =>
    intro hp
    exact absurd hp hnp
  | Or.inr hq =>
    intro hp
    exact hq
example : p ∨ False ↔ p := by
  constructor
  · show p ∨ False → p
    intro
    | Or.inl hp => exact hp
    | Or.inr hf => exact hf.elim
  · show p → p ∨ False
    intro hp
    exact Or.inl hp
example : p ∧ False ↔ False := by
  constructor
  · show p ∧ False → False
    intro h
    exact h.right.elim
  · show False → p ∧ False
    intro hf
    exact hf.elim
example : (p → q) → (¬q → ¬p) := by
  intro h
  intro hnq
  intro hp
  have hq : q := h hp
  exact hnq hq

end

/-!
Prove the following identities, replacing the `sorry` placeholders with actual
proofs. These require classical reasoning.
-/
section

variable (p q r : Prop)

#check Classical.em
#check Or.elim
example : (p → q ∨ r) → ((p → q) ∨ (p → r)) := by
  intro h
  match Classical.em p with
  | Or.inl hp =>
    match h hp with
    | Or.inl hq =>
      apply Or.inl
      intro hp
      exact hq
    | Or.inr hr =>
      apply Or.inr
      intro hp
      exact hr
  | Or.inr hnp =>
    have hp2q : p → q := by
      intro hp
      exact absurd hp hnp
    exact Or.inl hp2q
example : ¬(p ∧ q) → ¬p ∨ ¬q := by
  intro h
  match Classical.em p with
  | Or.inl hp =>
    match Classical.em q with
    | Or.inl hq =>
      have hpq : p ∧ q := And.intro hp hq
      exact absurd hpq h
    | Or.inr hnq => exact Or.inr hnq
  | Or.inr hnp => exact Or.inl hnp
example : ¬(p → q) → p ∧ ¬q := by
  intro hnp2q
  match Classical.em p with
  | Or.inl hp =>
    match Classical.em q with
    | Or.inl hq =>
      have hp2q : p → q := by
        intro hp
        exact hq
      exact absurd hp2q hnp2q
    | Or.inr hnq => exact And.intro hp hnq
  | Or.inr hnp =>
    have hp2q : p → q := by
      intro hp
      exact absurd hp hnp
    exact absurd hp2q hnp2q
example : (p → q) → (¬p ∨ q) := by
  intro hp2q
  match Classical.em p with
  | Or.inl hp =>
    have hq : q := hp2q hp
    exact Or.inr hq
  | Or.inr hnp => exact Or.inl hnp
example : (¬q → ¬p) → (p → q) := by
  intro hnq2np
  intro hp
  match Classical.em q with
  | Or.inl hq => exact hq
  | Or.inr hnq =>
    have hnp : ¬p := hnq2np hnq
    exact absurd hp hnp
example : p ∨ ¬p := by exact Classical.em p
example : (((p → q) → p) → p) := by
  intro h
  match Classical.em p with
  | Or.inl hp => exact hp
  | Or.inr hnp =>
    have hp2q : p → q := by
      intro hp
      exact absurd hp hnp
    exact h hp2q

end

#check Iff.elim
/-!
Prove `¬(p ↔ ¬p)` without using classical logic.
-/
section
example {p : Prop} : ¬(p ↔ ¬p) := by
  intro h
  apply h.elim
  intro hp2np hnp2p
  have hnp : ¬p := by
    intro hp
    have hnp : ¬p := hp2np hp
    exact hnp hp
  have hp : p := hnp2p hnp
  exact hnp hp
end

end PropositionsAndProofs

section QuantifiersAndEquality

/-!
1. Prove these equivalences:
  You should also try to understand why the reverse implication is not derivable
  in the last example.
-/
section Exercise1
variable (α : Type) (p q : α → Prop)

example : (∀ x, p x ∧ q x) ↔ (∀ x, p x) ∧ (∀ x, q x) := by
  constructor
  · intro h
    constructor
    · intro w
      exact (h w).left
    · intro w
      exact (h w).right
  · intro h
    intro w
    constructor
    · exact h.left w
    · exact h.right w
example : (∀ x, p x → q x) → (∀ x, p x) → (∀ x, q x) := by
  intro h
  intro hp
  intro w
  have hp : p w := hp w
  have hq : q w := h w hp
  exact hq
example : (∀ x, p x) ∨ (∀ x, q x) → ∀ x, p x ∨ q x := by
  intro
  | Or.inl hp =>
    intro w
    exact Or.inl $ hp w
  | Or.inr hq =>
    intro w
    exact Or.inr $ hq w

#check Exists.intro
#check Or.elim
example
: ∃ (α : Type) (p q : α → Prop),
  ¬((∀ x, p x ∨ q x) → (∀ x, p x) ∨ (∀ x, q x)) := by
  let hα : Type := Bool
  let hp : hα → Prop := λ x ↦ x = true
  let hq : hα → Prop := λ x ↦ x = false
  apply Exists.intro hα
  apply Exists.intro hp
  apply Exists.intro hq
  intro h
  have : ∀ x, hp x ∨ hq x := by
    intro
    | true => exact Or.inl $ Eq.refl true
    | false => exact Or.inr $ Eq.refl false
  have h : (∀ x, hp x) ∨ (∀ x, hq x) := h this
  have hn : ¬((∀ x, hp x) ∨ (∀ x, hq x)) := by
    intro
    | Or.inl h => exact Bool.false_ne_true $ h false
    | Or.inr h => exact Bool.false_ne_true ∘ Eq.symm $ h true
  exact hn h
end Exercise1

/-!
2. It is often possible to bring a component of a formula outside a universal
  quantifier, when it does not depend on the quantified variable. Try proving
  these (one direction of the second of these requires classical logic):
-/
section Exercise2
variable (α : Type) (p q : α → Prop)
variable (r : Prop)

example : α → ((∀ x : α, r) ↔ r) := by
  intro w
  constructor
  · intro hr
    exact hr w
  · intro hr
    intro v
    exact hr
example : (∀ x, p x ∨ r) ↔ (∀ x, p x) ∨ r := by
  constructor
  · intro h
    match Classical.em r with
    | Or.inl hr => exact Or.inr hr
    | Or.inr hnr =>
      apply Or.inl
      intro w
      match h w with
      | Or.inl hp => exact hp
      | Or.inr hr => exact absurd hr hnr
  · intro h
    intro w
    match h with
    | Or.inl hp => exact Or.inl $ hp w
    | Or.inr hr => exact Or.inr hr
example : (∀ x, r → p x) ↔ (r → ∀ x, p x) := by
  constructor
  · intro h
    intro hr
    intro w
    exact h w hr
  · intro h
    intro w
    intro hr
    exact h hr w
end Exercise2

/-!
3. Consider the "barber paradox", that is, the claim that in a certain town
  there is a (male) barber that shaves all and only the men who do not shave
  themselves. Prove that this is a contradiction:
-/
section Exercise3
variable (men : Type) (barber : men)
variable (shaves : men → men → Prop)

example (h : ∀ x : men, shaves barber x ↔ ¬shaves x x) : False := by
  let x : men := barber
  have : shaves barber barber ↔ ¬shaves barber barber := h x
  let a : Prop := shaves barber barber
  let na : Prop := ¬shaves barber barber
  apply this.elim
  intro ha2na
  intro hna2a
  have hna : na := by
    intro ha
    have hna := ha2na ha
    exact hna ha
  have ha : a := by
    exact hna2a hna
  exact hna ha
end Exercise3

/-!
5. Prove as many of the identities listed in the Existential Quantifier section
  as you can.
  > What follows are some common identities involving the existential
  > quantifier. In the exercises below, we encourage you to prove as many as you
  > can. We also leave it to you to determine which are nonconstructive, and
  > hence require some form of classical reasoning.
-/
section Exercise5
variable (α : Type) (p q : α → Prop)
variable (r : Prop)

#check Exists.elim
example : (∃ _x : α, r) → r := by
  intro h
  apply h.elim
  intro h
  intro hr
  exact hr
#check Exists.intro
example (a : α) : r → (∃ _x : α, r) := by
  intro hr
  apply Exists.intro a
  exact hr
example : (∃ x, p x ∧ r) ↔ (∃ x, p x) ∧ r := by
  constructor
  case mp =>
    intro h
    apply h.elim
    intro w
    intro (And.intro hp hr)
    constructor
    case left =>
      show ∃ x, p x
      apply Exists.intro w
      exact hp
    case right =>
      exact hr
  case mpr =>
    intro h
    apply h.left.elim
    intro w
    intro hp
    apply Exists.intro w
    exact And.intro hp h.right
example : (∃ x, p x ∨ q x) ↔ (∃ x, p x) ∨ (∃ x, q x) := by
  constructor
  case mp =>
    intro h
    apply h.elim
    intro w
    intro
    | Or.inl hp =>
      apply Or.inl
      apply Exists.intro w
      exact hp
    | Or.inr hq =>
      apply Or.inr
      apply Exists.intro w
      exact hq
  case mpr =>
    intro
    | Or.inl h =>
      apply h.elim
      intro w
      intro hp
      apply Exists.intro w
      exact Or.inl hp
    | Or.inr h =>
      apply h.elim
      intro w
      intro hq
      apply Exists.intro w
      exact Or.inr hq

example : (∀ x, p x) ↔ ¬(∃ x, ¬p x) := by
  constructor
  · intro h
    intro h'
    apply h'.elim
    intro w
    intro hnp
    have hp : p w := h w
    exact hnp hp
  · intro h
    intro w
    apply Classical.byContradiction
    intro hnp
    apply h
    apply Exists.intro w
    exact hnp
example : (∃ x, p x) ↔ ¬(∀ x, ¬p x) := by
  constructor
  · intro h
    intro h'
    apply h.elim
    intro w
    intro hp
    have hnp : ¬p w := h' w
    exact hnp hp
  · intro h
    apply Classical.byContradiction
    intro h'
    apply h
    intro w
    intro hp
    apply h'
    apply Exists.intro w
    exact hp
example : (¬∃ x, p x) ↔ (∀ x, ¬p x) := by
  constructor
  · intro h
    intro w
    intro hp
    apply h
    apply Exists.intro w
    exact hp
  · intro h
    intro h'
    apply h'.elim
    intro w
    intro hp
    have hnp : ¬p w := h w
    exact hnp hp
example : (¬∀ x, p x) ↔ (∃ x, ¬p x) := by
  constructor
  · intro h
    apply Classical.byContradiction
    intro h'
    apply h
    intro w
    apply Classical.byContradiction
    intro hnp
    apply h'
    apply Exists.intro w
    exact hnp
  · intro h
    intro h'
    apply h.elim
    intro w
    intro hnp
    apply hnp
    exact h' w

example : (∀ x, p x → r) ↔ (∃ x, p x) → r := by
  constructor
  · intro h
    intro h'
    apply h'.elim
    intro w
    intro hp
    exact h w hp
  · intro h
    intro w
    intro hp
    have : ∃ x, p x := by
      apply Exists.intro w
      exact hp
    exact h this
example (a : α) : (∃ x, p x → r) ↔ (∀ x, p x) → r := by
  constructor
  · intro h
    intro h'
    apply h.elim
    intro w
    intro hp2r
    have hp : p w := h' w
    exact hp2r hp
  · intro h
    apply Classical.byContradiction
    intro h'
    have : ∀ x, p x := by
      intro w
      apply Classical.byContradiction
      intro hnp
      apply h'
      apply Exists.intro w
      intro hp
      exact absurd hp hnp
    have hr : r := h this
    apply h'
    apply Exists.intro a
    intro hp
    exact hr
example (a : α) : (∃ x, r → p x) ↔ (r → ∃ x, p x) := by
  constructor
  · intro h
    intro hr
    apply h.elim
    intro w
    intro hr2hp
    apply Exists.intro w
    exact hr2hp hr
  · intro h
    match Classical.em r with
    | Or.inl hr =>
      apply (h hr).elim
      intro w
      intro hp
      apply Exists.intro w
      intro hr
      exact hp
    | Or.inr hnr =>
      apply Classical.byContradiction
      intro h'
      apply hnr
      have : ∃ x, r → p x := by
        apply Exists.intro a
        intro hr
        exact absurd hr hnr
      exact absurd this h'

end Exercise5

end QuantifiersAndEquality

end Exercise1

/-!
2. Use tactic combinators to obtain a one-line proof of the following:
-/
section Exercise2

example (p q r : Prop) (hp : p)
: (p ∨ q ∨ r) ∧ (q ∨ p ∨ r) ∧ (q ∨ r ∨ p) := by
  -- If you don't understand, maybe you will want to read the comment I wrote
  -- for example repeat first.
  repeat first
  | apply And.intro
    --↑ Do not use `constructor` to instead it, because we only want `And.intro`
    --↑ successed, but not want `Or.inl` successed.
  | apply Or.inl; assumption
  | apply Or.inr; assumption
  | apply Or.inr

end Exercise2

end Exercises

